const express = require('express')
const app = express()
const config = require('./config/server')
const pg = require('./utils/pg')
const MiddleWare = require('./middleware/middleware')
const User = require('./routers/user')
const Login = require('./routers/login')
const Directions = require('./routers/directions')
const Teachers = require('./routers/teachers')
const Guruh = require('./routers/guruh')
const Davomat = require("./routers/davomat")
const Tolov = require("./routers/tolov")
const Paid = require("./routers/paid")
const Courses = require("./routers/courses")
const Pariticepents = require("./routers/participent")
const AnonymChat = require("./routers/anonym_chat")
const Students = require("./routers/student")
const Info_From_Client = require('./routers/info_from_client')

app.use( express.json() )
app.use( MiddleWare.middle )
app.use( User )
app.use( Login )
app.use( Directions )
app.use( Teachers )
app.use( Guruh )
app.use( Davomat )
app.use( Tolov )
app.use( Paid )
app.use( Pariticepents)
app.use( Courses )
app.use( AnonymChat )
app.use( Students )
app.use( Info_From_Client )


app.listen(config.PORT,()=>console.log(`http://localhost:${config.PORT}`))
